language: cpp
compiler: g++
sudo: required
dist: xenial
os:
  - linux

compiler:
  - gcc
  # - clang

branches:
  only: master

matrix:
  fast-finish: true

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - python-yaml
      - gcc-9
      - g++-9
      # - llvm
      # - clang
      - libc++-dev
      - libgmp3-dev
      - libmpfr-dev
      - libmpfrc++-dev

script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 50 --slave /usr/bin/g++ g++ /usr/bin/g++-9
  - make
  - ./test/bin/test
