#!/bin/bash

term=2
len=10

[ $# -ge 1 ] && {
  len=$1; shift
}
[ $# -eq 1 ] && {
  term=$1; shift
}

for i in $(seq "$len"); do
  printf "%s\n" "$(perl -e "print($term ** $i)")"
  ((cur *= term))
done
